### PR TITLE
create new.txt file

### PR DESCRIPTION
**Pull request by nadimalabbas**
created a new text file new.txt

edited pull request body

### CODE REVIEW

**Review by nadtesttest — CHANGES_REQUESTED** [review]
I requested these changes

**Comment by nadimalabbas** [comment]
yes

**Review by nadtesttest — CHANGES_REQUESTED** [review]
2nd request for changes

**Review by nadtesttest — CHANGES_REQUESTED** [review]
3rd request of changes after adding types for pull_request_review event

**Comment by nadimalabbas** [comment]
remove wainting for update

**Pull request closed without merging**
